replicaCount: 5

image:
  tag: "1.21"

app:
  environment: "production"
  version: "v2.0.0"

service:
  type: LoadBalancer

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70