replicaCount: 2

image:
  tag: "1.20"

app:
  environment: "development"
  version: "v2.0.0-dev"

service:
  type: LoadBalancer

resources:
  limits:
    cpu: 200m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 32Mi
